"use client";

import { useState } from "react";

/**
 * "⚡ TL;DR" button — asks the self-hosted AI gateway (via /api/ai-tldr)
 * to summarize the current post. Server-side route does the LLM call,
 * so the gateway URL/key never reach the browser.
 */
export default function TLDRButton({ slug }: { slug: string }) {
  const [state, setState] = useState<"idle" | "loading" | "done" | "error">(
    "idle"
  );
  const [summary, setSummary] = useState("");

  async function run() {
    if (state === "loading") return;
    setState("loading");
    setSummary("");
    try {
      const res = await fetch("/api/ai-tldr", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ slug }),
      });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = (await res.json()) as { summary?: string };
      if (!data.summary) throw new Error("empty summary");
      setSummary(data.summary);
      setState("done");
    } catch {
      setState("error");
    }
  }

  return (
    <div className="mt-8">
      <button
        type="button"
        onClick={run}
        disabled={state === "loading"}
        className="inline-flex items-center gap-2 rounded border border-accent/60 bg-accent/10 px-4 py-2 font-mono text-sm text-accent transition-colors hover:bg-accent hover:text-bg disabled:cursor-not-allowed disabled:opacity-60"
      >
        <span aria-hidden="true">⚡</span>
        {state === "loading" ? "summarizing…" : "TL;DR"}
      </button>

      {state === "done" && summary && (
        <div className="mt-4 rounded border border-line bg-panel p-5">
          <p className="font-mono text-xs uppercase tracking-wider text-dim">
            ⚡ TL;DR — generated by your homelab AI
          </p>
          <div className="mt-2 whitespace-pre-wrap text-sm leading-relaxed text-fg">
            {summary}
          </div>
        </div>
      )}

      {state === "error" && (
        <p className="mt-3 font-mono text-xs text-red-400">
          Could not summarize right now — try again in a bit.
        </p>
      )}
    </div>
  );
}
